food_entity_template = [
    "Good {}",
    "all-you-can-eat {} bar is the prime attraction and is far more interesting than any of the entrees",
    "{} is a very good option",
    "So our {} was not good from start to finish",
    "The {} is a throwback feel",
    "{} are back",
    "That did not say delicious {} ahead",
    "The {} was not great",
    "The {} was great",
    "The {} was a massive disappointment",
    "The {} was a incredible",
    "I was being robbed that I had to pay for {} that was not as good as an average person would expect quality wise",
    "The place needs something more than just {} to win as a restaurant",
    "If I order {}, I specifically order them well done",
    "Yesterday I ordered the {} and I loved it",
    "I will say the {} is definitely not worth $15 though",
    "Good quality {}",
    "{} overall was good, as well as {}",
    "My friend ordered a {}",
    "My meal was a {}",
    "The {} alone drew us back again and again for a fresh and healthy meal",
    "Tonight we stopped in for a couple of {}", 
    "brought out a plate of rock-hard {} looking things with dried out, stringy {} inside and a pile of underdone, whitish, {}",
    "The {} and {} with {} was a incredible",
    "We had the {} and {} with {}",
    "I had the {} and {} with {}",
    "I recommend ordering one of the {} with the {}",
    "The {} and {} was a incredible",
    "{} and {} is a very good option",
    "I really enjoyed the {} and {}",
    "Then I ordered {} and {}",
    "I suggest ordering a {} and adding the {} to it",
    "{} was less than good and the {} we ordered came out warmish",
    "Ordered {} with no {}",
    "My daughters friend ordered {} with {}",
    "The {} was tasteless and the {} was decent",
]